/**
 * SKU Audit Trail Types — Phase T17.5
 *
 * Immutable event log + snapshot model for full SKU lifecycle traceability.
 * Supports internal review, operator audits, and quality compliance queries.
 *
 * Governance:
 *   - Events are never mutated after write.
 *   - Actor identity is required but may be UNKNOWN when not yet wired.
 *   - Snapshots are selective (not after every interaction).
 */

// ---------------------------------------------------------------------------
// Event types
// ---------------------------------------------------------------------------

export type SkuAuditEventType =
  | 'DRAWING_UPLOADED'
  | 'BOM_UPLOADED'
  | 'DOC_TYPE_CONFIRMED'
  | 'FIELD_CONFIRMED'
  | 'WIRE_OVERRIDE_APPLIED'
  | 'SKU_WIRE_ADDED'
  | 'SKU_WIRE_EDITED'
  | 'SKU_WIRE_DELETED'
  | 'BRANCH_DECLARED'
  | 'TOPOLOGY_WARNING_RESOLVED'
  | 'WIRE_IDENTITIES_RECALCULATED'
  | 'KOMAX_CUT_SHEET_GENERATED'
  | 'KOMAX_BATCHES_GENERATED'
  | 'KOMAX_PROGRAM_GENERATED'
  | 'KOMAX_PROGRAM_EXPORTED'
  | 'ENDPOINT_PROCESS_ENRICHED'
  | 'SKU_READY_TO_COMMIT'
  | 'SKU_COMMITTED';

// ---------------------------------------------------------------------------
// Event record (immutable once written)
// ---------------------------------------------------------------------------

export interface SkuAuditEvent {
  /** UUID v4 — generated at write time. */
  id: string;
  /**
   * Normalized part number used as the stable SKU identifier.
   * Rule: trim whitespace from confirmedPartNumber ?? proposedPartNumber.
   */
  skuKey: string;
  eventType: SkuAuditEventType;
  /** ISO 8601 UTC timestamp. */
  timestamp: string;

  actorType: 'USER' | 'SYSTEM' | 'UNKNOWN';
  /**
   * Human-readable actor name.
   * Use "Unknown Operator" when actor identity is not yet wired.
   */
  actorName?: string | null;

  /** One-line human-readable description of what happened. */
  summary: string;
  /** Operator-supplied justification (present for overrides, deletions). */
  reason?: string | null;

  /** Structured detail for the event — shape depends on eventType. */
  payload?: Record<string, unknown> | null;
  /** Snapshot of relevant state BEFORE the change (for diff display). */
  beforeState?: Record<string, unknown> | null;
  /** Snapshot of relevant state AFTER the change (for diff display). */
  afterState?: Record<string, unknown> | null;

  /** IDs of documents/files that triggered this event. */
  sourceArtifactIds?: string[] | null;
  /** IDs of outputs (CSV files, etc.) produced by this event. */
  generatedArtifactIds?: string[] | null;
}

/**
 * Input shape for event creation.
 * `id` and `timestamp` are auto-generated by buildAuditEvent() if omitted.
 */
export type SkuAuditEventInput = Omit<SkuAuditEvent, 'id' | 'timestamp'> & {
  id?: string;
  timestamp?: string;
};

// ---------------------------------------------------------------------------
// Snapshot record
// ---------------------------------------------------------------------------

export type SkuAuditSnapshotType =
  | 'INGESTION_BASELINE'
  | 'PRE_COMMIT'
  | 'COMMITTED'
  | 'MANUAL_CHECKPOINT';

export interface SkuAuditSnapshot {
  id: string;
  skuKey: string;
  timestamp: string;
  snapshotType: SkuAuditSnapshotType;
  /**
   * Serialised effective harness state at the moment of snapshot.
   * Should include: effectiveConnectivity summary, topologySummary,
   * wireIdentitySummary, decision, and Komax cut sheet summary if available.
   */
  effectiveState: Record<string, unknown>;
  summary: string;
}

export type SkuAuditSnapshotInput = Omit<SkuAuditSnapshot, 'id' | 'timestamp'> & {
  id?: string;
  timestamp?: string;
};
