import { Validation } from '../types/validation';

export const TRANE_VALIDATIONS: Validation[] = [
  // Pre-Acknowledgement Validations (5)
  {
    id: 'process_flow',
    name: 'Process Flow Diagram',
    category: 'pre-ack',
    validation_type: 'document',
    required: true,
    requires_approval: false,
    status: 'not_started',
  },
  {
    id: 'dfmea',
    name: 'DFMEA',
    category: 'pre-ack',
    validation_type: 'document',
    required: true,
    requires_approval: false,
    status: 'not_started',
  },
  {
    id: 'pfmea',
    name: 'PFMEA',
    category: 'pre-ack',
    validation_type: 'document',
    required: true,
    requires_approval: false,
    status: 'not_started',
  },
  {
    id: 'control_plan',
    name: 'Control Plan',
    category: 'pre-ack',
    validation_type: 'document',
    required: true,
    requires_approval: false,
    status: 'not_started',
  },
  {
    id: 'measurement_plan',
    name: 'Measurement Plan',
    category: 'pre-ack',
    validation_type: 'document',
    required: true,
    requires_approval: false,
    status: 'not_started',
  },

  // Post-Acknowledgement Validations (9)
  {
    id: 'dimensional_results',
    name: 'Dimensional Results',
    category: 'post-ack',
    validation_type: 'data',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'material_certs',
    name: 'Material Certifications',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'performance_tests',
    name: 'Performance Test Results',
    category: 'post-ack',
    validation_type: 'data',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'msa',
    name: 'MSA',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'capability',
    name: 'Capability Studies',
    category: 'post-ack',
    validation_type: 'data',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'psw',
    name: 'PSW',
    category: 'post-ack',
    validation_type: 'approval',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'packaging',
    name: 'Packaging Approval',
    category: 'post-ack',
    validation_type: 'approval',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
  {
    id: 'final_control_plan',
    name: 'Final Control Plan',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    status: 'not_started',
  },
];
