import { Validation } from '../types/validation';

/**
 * Phase 3E.8 - PPAP Requirement Restructure
 * 
 * Trane validation template with clear separation:
 * - Pre-Ack: Readiness validations (boolean checks, not documents)
 * - Post-Ack: Submission documents (REQUIRED/CONDITIONAL)
 */
export const TRANE_VALIDATIONS: Validation[] = [
  // Pre-Acknowledgement Readiness (6 validation checks)
  {
    id: 'drawing_verification',
    name: 'Drawing Verification',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'bom_review',
    name: 'BOM Review',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'tooling_validation',
    name: 'Tooling Validation',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'material_availability',
    name: 'Material Availability Check',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'psw_presence',
    name: 'PSW Presence',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'discrepancy_resolution',
    name: 'Discrepancy Resolution',
    category: 'pre-ack',
    validation_type: 'check',
    required: true,
    requires_approval: false,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },

  // Post-Acknowledgement REQUIRED Documents (10)
  {
    id: 'psw',
    name: 'PSW',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'ballooned_drawing',
    name: 'Ballooned Drawing',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'fair',
    name: 'First Article Inspection Report (FAIR)',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'control_plan',
    name: 'Control Plan',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'pfmea',
    name: 'PFMEA',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'dfmea',
    name: 'DFMEA',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'dimensional_results',
    name: 'Dimensional Results',
    category: 'post-ack',
    validation_type: 'data',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'material_certs',
    name: 'Material Certifications',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'msa',
    name: 'MSA',
    category: 'post-ack',
    validation_type: 'document',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },
  {
    id: 'capability_studies',
    name: 'Capability Studies',
    category: 'post-ack',
    validation_type: 'data',
    required: true,
    requires_approval: true,
    requirement_level: 'REQUIRED',
    status: 'not_started',
  },

  // Post-Acknowledgement CONDITIONAL Documents (5)
  {
    id: 'packaging_approval',
    name: 'Packaging Approval',
    category: 'post-ack',
    validation_type: 'approval',
    required: false,
    requires_approval: true,
    requirement_level: 'CONDITIONAL',
    status: 'not_started',
  },
  {
    id: 'appearance_approval',
    name: 'Appearance Approval',
    category: 'post-ack',
    validation_type: 'approval',
    required: false,
    requires_approval: true,
    requirement_level: 'CONDITIONAL',
    status: 'not_started',
  },
  {
    id: 'performance_testing',
    name: 'Performance Testing',
    category: 'post-ack',
    validation_type: 'data',
    required: false,
    requires_approval: true,
    requirement_level: 'CONDITIONAL',
    status: 'not_started',
  },
  {
    id: 'barcode_standards',
    name: 'Barcode Standards',
    category: 'post-ack',
    validation_type: 'document',
    required: false,
    requires_approval: true,
    requirement_level: 'CONDITIONAL',
    status: 'not_started',
  },
  {
    id: 'assembly_standards',
    name: 'Assembly Standards',
    category: 'post-ack',
    validation_type: 'document',
    required: false,
    requires_approval: true,
    requirement_level: 'CONDITIONAL',
    status: 'not_started',
  },
];
