/**
 * Dimensional Results Sheet Handler — STUB
 * V3.2F
 *
 * Dimensional results are external data: they must be provided by the
 * customer or QE team and cannot be generated by the Copilot.
 *
 * Per V3.2E output contract, the document activation input for "dimensional"
 * should be set to "external_required", which causes the Copilot to emit
 * a missing_data_requests entry rather than attempting generation.
 *
 * This stub exists to make the routing layer exhaustive and to surface a
 * clear error if "dimensional" data reaches the injection engine unexpectedly.
 */

import ExcelJS from 'exceljs';

export function handleDimensional(
  _workbook: ExcelJS.Workbook,
  _data: unknown
): never {
  throw new Error(
    '[DimensionalSheet] External data required. ' +
    'Dimensional results must be provided by the customer or QE team. ' +
    'This document type cannot be generated by the Copilot. ' +
    'Set activation state to "external_required" in the Document Activation Input.'
  );
}
