/**
 * Material Test Results Sheet Handler — STUB
 * V3.2F
 *
 * Material test results are external data: they must be provided by the
 * supplier lab and cannot be generated by the Copilot.
 *
 * Per V3.2E output contract, the document activation input for "material_test"
 * should be set to "external_required", which causes the Copilot to emit
 * a missing_data_requests entry rather than attempting generation.
 *
 * This stub exists to make the routing layer exhaustive and to surface a
 * clear error if "material_test" data reaches the injection engine unexpectedly.
 */

import ExcelJS from 'exceljs';

export function handleMaterialTest(
  _workbook: ExcelJS.Workbook,
  _data: unknown
): never {
  throw new Error(
    '[MaterialTestSheet] External data required. ' +
    'Material test results must be provided by the supplier lab. ' +
    'This document type cannot be generated by the Copilot. ' +
    'Set activation state to "external_required" in the Document Activation Input.'
  );
}
