'use client';

import { useState } from 'react';
import { CopilotDraft } from '../types/copilotTypes';

interface CopilotDraftPreviewProps {
  draft: CopilotDraft;
  onAccept: (draft: CopilotDraft) => void;
  onRequestChanges: (feedback: string) => void;
}

export function CopilotDraftPreview({
  draft,
  onAccept,
  onRequestChanges
}: CopilotDraftPreviewProps) {
  const [showFeedbackInput, setShowFeedbackInput] = useState(false);
  const [feedbackText, setFeedbackText] = useState('');
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['confidence']));

  if (draft.type !== 'draft' || !draft.documentData) {
    return null;
  }

  const { documentData, metadata } = draft;
  const hasUncertainFields = metadata.uncertainFields.length > 0;
  const hasAssumptions = metadata.assumptions.length > 0;

  const toggleSection = (section: string) => {
    setExpandedSections(prev => {
      const newSet = new Set(prev);
      if (newSet.has(section)) {
        newSet.delete(section);
      } else {
        newSet.add(section);
      }
      return newSet;
    });
  };

  const handleAccept = () => {
    onAccept(draft);
  };

  const handleSubmitFeedback = () => {
    if (feedbackText.trim()) {
      onRequestChanges(feedbackText.trim());
      setFeedbackText('');
      setShowFeedbackInput(false);
    }
  };

  const getConfidenceColor = (confidence: string) => {
    switch (confidence) {
      case 'high':
        return 'bg-green-100 text-green-800 border-green-300';
      case 'medium':
        return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'low':
        return 'bg-red-100 text-red-800 border-red-300';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-300';
    }
  };

  const getConfidenceIcon = (confidence: string) => {
    switch (confidence) {
      case 'high':
        return '✅';
      case 'medium':
        return '⚠️';
      case 'low':
        return '❌';
      default:
        return '❓';
    }
  };

  return (
    <div className="w-full space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h4 className="text-lg font-semibold text-gray-900">
            {documentData.templateId} Draft Ready
          </h4>
          <p className="text-sm text-gray-600 mt-1">
            Generated by Claude • Review and accept or request changes
          </p>
        </div>
        <div className={`px-3 py-1 rounded-full text-sm font-medium border ${getConfidenceColor(metadata.confidence)}`}>
          {getConfidenceIcon(metadata.confidence)} {metadata.confidence.toUpperCase()} Confidence
        </div>
      </div>

      {/* AI Provenance Metadata */}
      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        {/* Confidence Section */}
        <button
          onClick={() => toggleSection('confidence')}
          className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold text-gray-900">AI Confidence & Metadata</span>
            <span className="text-xs text-gray-500">
              ({metadata.tokenCount.total.toLocaleString()} tokens)
            </span>
          </div>
          <span className="text-gray-400">
            {expandedSections.has('confidence') ? '▼' : '▶'}
          </span>
        </button>
        
        {expandedSections.has('confidence') && (
          <div className="px-4 pb-4 space-y-3 border-t border-gray-100">
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-gray-600">Model:</span>
                <span className="ml-2 font-mono text-xs text-gray-900">{metadata.model}</span>
              </div>
              <div>
                <span className="text-gray-600">Template:</span>
                <span className="ml-2 font-mono text-xs text-gray-900">{metadata.promptTemplateId}</span>
              </div>
              <div>
                <span className="text-gray-600">Generated:</span>
                <span className="ml-2 text-xs text-gray-900">
                  {new Date(metadata.generatedAt).toLocaleString()}
                </span>
              </div>
              <div>
                <span className="text-gray-600">Token Usage:</span>
                <span className="ml-2 text-xs text-gray-900">
                  {metadata.tokenCount.input} in / {metadata.tokenCount.output} out
                </span>
              </div>
            </div>
          </div>
        )}

        {/* Uncertain Fields Section */}
        {hasUncertainFields && (
          <>
            <button
              onClick={() => toggleSection('uncertain')}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors border-t border-gray-200"
            >
              <div className="flex items-center gap-2">
                <span className="text-sm font-semibold text-yellow-800">
                  ⚠️ Uncertain Fields ({metadata.uncertainFields.length})
                </span>
              </div>
              <span className="text-gray-400">
                {expandedSections.has('uncertain') ? '▼' : '▶'}
              </span>
            </button>
            
            {expandedSections.has('uncertain') && (
              <div className="px-4 pb-4 border-t border-gray-100">
                <ul className="space-y-2 text-sm">
                  {metadata.uncertainFields.map((field, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-yellow-600 mt-0.5">•</span>
                      <span className="text-gray-900 font-mono text-xs">{field}</span>
                    </li>
                  ))}
                </ul>
                <p className="text-xs text-yellow-700 mt-3 bg-yellow-50 px-3 py-2 rounded">
                  These fields require review. Claude was uncertain about the values and recommends verification.
                </p>
              </div>
            )}
          </>
        )}

        {/* Assumptions Section */}
        {hasAssumptions && (
          <>
            <button
              onClick={() => toggleSection('assumptions')}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors border-t border-gray-200"
            >
              <div className="flex items-center gap-2">
                <span className="text-sm font-semibold text-blue-800">
                  📋 Assumptions Made ({metadata.assumptions.length})
                </span>
              </div>
              <span className="text-gray-400">
                {expandedSections.has('assumptions') ? '▼' : '▶'}
              </span>
            </button>
            
            {expandedSections.has('assumptions') && (
              <div className="px-4 pb-4 border-t border-gray-100">
                <ul className="space-y-2 text-sm">
                  {metadata.assumptions.map((assumption, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-blue-600 mt-0.5">•</span>
                      <span className="text-gray-700">{assumption}</span>
                    </li>
                  ))}
                </ul>
                <p className="text-xs text-blue-700 mt-3 bg-blue-50 px-3 py-2 rounded">
                  Claude made these assumptions during generation. Verify they align with your requirements.
                </p>
              </div>
            )}
          </>
        )}

        {/* Document Preview Section */}
        <button
          onClick={() => toggleSection('preview')}
          className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors border-t border-gray-200"
        >
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold text-gray-900">
              📄 Document Preview
            </span>
            <span className="text-xs text-gray-500">
              ({Object.keys(documentData.fields).length} fields)
            </span>
          </div>
          <span className="text-gray-400">
            {expandedSections.has('preview') ? '▼' : '▶'}
          </span>
        </button>
        
        {expandedSections.has('preview') && (
          <div className="px-4 pb-4 border-t border-gray-100 max-h-96 overflow-y-auto">
            <div className="bg-gray-50 rounded p-3 text-xs font-mono">
              <pre className="whitespace-pre-wrap text-gray-700">
                {JSON.stringify(documentData.fields, null, 2)}
              </pre>
            </div>
            <p className="text-xs text-gray-600 mt-2">
              Full document editor available after accepting draft
            </p>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button
          onClick={handleAccept}
          className="flex-1 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium"
        >
          ✅ Accept Draft
        </button>
        <button
          onClick={() => setShowFeedbackInput(!showFeedbackInput)}
          className="flex-1 px-6 py-3 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 transition-colors font-medium"
        >
          ✏️ Request Changes
        </button>
      </div>

      {/* Feedback Input */}
      {showFeedbackInput && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 space-y-3">
          <label className="block text-sm font-medium text-gray-900">
            What changes would you like Claude to make?
          </label>
          <textarea
            value={feedbackText}
            onChange={(e) => setFeedbackText(e.target.value)}
            placeholder="Describe the changes you'd like (e.g., 'Increase severity ratings for safety-critical operations', 'Add more detail to failure mode descriptions')..."
            rows={4}
            className="w-full px-3 py-2 border border-yellow-300 rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-500 resize-none"
          />
          <div className="flex gap-2">
            <button
              onClick={handleSubmitFeedback}
              disabled={!feedbackText.trim()}
              className="px-4 py-2 bg-yellow-600 text-white rounded-md hover:bg-yellow-700 transition-colors disabled:bg-gray-300 disabled:cursor-not-allowed font-medium text-sm"
            >
              Send to Claude
            </button>
            <button
              onClick={() => {
                setShowFeedbackInput(false);
                setFeedbackText('');
              }}
              className="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 transition-colors font-medium text-sm"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Warning if Low Confidence */}
      {metadata.confidence === 'low' && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <div className="flex items-start gap-3">
            <span className="text-red-600 text-xl">⚠️</span>
            <div>
              <h5 className="text-sm font-semibold text-red-900">Low Confidence Warning</h5>
              <p className="text-sm text-red-700 mt-1">
                Claude has low confidence in this draft. Consider requesting changes or providing additional context.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
