/**
 * Control Plan Workbook Cell Mapping
 * Phase V2.7B - Control Plan template-specific cell map for workbook injection
 * 
 * Target Workbook: QUAL TM 0027 - 01 PPAP Package.xlsx
 * Target Sheet: "7_Process Control Plan - Form"
 * 
 * Sheet Structure (from W2A inspection):
 * - Dimensions: 13 cols x 59 rows
 * - Example sheet: "7 - Control Plan Example" (Sheet 32) shows 13 cols x 25 rows with data
 * - Row-based data structure for process control steps
 * 
 * The wizard template generates row-based control plan data with fields:
 * - stepNumber (process step sequence)
 * - process (process description from BOM operations)
 * - machine (machine/device/tool from BOM resources)
 * - characteristic (product/process characteristic - user input)
 * - method (control method - suggested with dropdown)
 * - sampleSize (sample size/frequency - suggested with dropdown)
 * 
 * Current mapping: Header + row-level injection for defensible fields only
 * 
 * NOTE: Column mappings are estimated based on typical PPAP Control Plan structure.
 * Actual cell addresses should be verified against the workbook before production use.
 * Fields not reliably generated by the wizard are intentionally left unmapped.
 */

import { WorkbookCellMap } from '../excelTemplateInjector';

export const CONTROL_PLAN_WORKBOOK_MAP: WorkbookCellMap = {
  sheetName: '7_Process Control Plan - Form',
  
  // Header fields (part number typically in upper area of form)
  // Estimated cell location - may need adjustment after workbook inspection
  headerMappings: [
    {
      fieldKey: 'partNumber',
      cellAddress: 'B2', // Estimated - adjust after workbook inspection
      label: 'Part Number'
    }
  ],
  
  // Row-based data injection for control plan rows
  rowMappings: {
    dataFieldKey: 'controlPlanRows', // Array field from wizard template
    startRow: 10, // Estimated starting row - typical for PPAP forms with header area
    columnMappings: [
      {
        fieldKey: 'stepNumber',
        column: 'A',
        label: 'Process Step Number'
      },
      {
        fieldKey: 'process',
        column: 'B',
        label: 'Process Name/Operation Description'
      },
      {
        fieldKey: 'machine',
        column: 'C',
        label: 'Machine/Device/Tool'
      },
      {
        fieldKey: 'characteristic',
        column: 'D',
        label: 'Product/Process Characteristic'
      },
      {
        fieldKey: 'method',
        column: 'E',
        label: 'Control Method'
      },
      {
        fieldKey: 'sampleSize',
        column: 'F',
        label: 'Sample Size/Frequency'
      }
      // Additional Control Plan columns (reaction plan, control limits, etc.) 
      // are intentionally unmapped as the wizard does not currently generate them.
      // These should remain blank for operator/engineer completion.
    ]
  }
};
