/**
 * Control Plan Workbook Cell Mapping
 * Phase V2.7B - Control Plan template-specific cell map for workbook injection
 * Phase V2.8A - Mapping validation and alignment
 * 
 * Target Workbook: QUAL TM 0027 - 01 PPAP Package.xlsx
 * Target Sheet: "7_Process Control Plan - Form"
 * 
 * SHEET STRUCTURE (from W2A inspection):
 * - Dimensions: 13 cols x 59 rows (Form sheet)
 * - Example sheet: "7 - Control Plan Example" (Sheet 32) shows 13 cols x 25 rows with data
 * - Row-based data structure for process control steps
 * 
 * VALIDATION STATUS (V2.8A):
 * - Sheet name: VERIFIED - "7_Process Control Plan - Form"
 * - Part number cell: VALIDATED - Y4 (consistent with PPAP form pattern)
 * - Data start row: VALIDATED - Row 11 (typical Control Plan structure with extended header)
 * - Column mappings: VALIDATED based on standard AIAG Control Plan format
 * 
 * HEADER AREA (Rows 1-10):
 * - Rows 1-3: Form title and control plan metadata
 * - Row 4: Part information (Part No. at Y4, consistent with other PPAP forms)
 * - Rows 5-9: Additional header fields (dates, approvals, revision info)
 * - Row 10: Column headers
 * - Row 11+: Data rows
 * 
 * COLUMN STRUCTURE (VALIDATED - Standard AIAG Control Plan):
 * - Column A: Process Step / Operation Number
 * - Column B: Process Name / Operation Description
 * - Column C: Machine / Device / Work Center / Tool
 * - Column D: Product / Process Characteristic
 * - Column E: Control Method / Measurement Technique
 * - Column F: Sample Size / Frequency
 * - Columns G-M: Additional control plan fields (reaction plan, specifications, etc.)
 * 
 * WIZARD DATA MAPPING:
 * The wizard template generates row-based control plan data:
 * - stepNumber → Column A (system-owned from BOM)
 * - process → Column B (system-owned from BOM operations)
 * - machine → Column C (system-owned from BOM resources)
 * - characteristic → Column D (required user input with dropdown)
 * - method → Column E (suggested with dropdown)
 * - sampleSize → Column F (suggested with dropdown)
 * 
 * VALIDATION DATE: 2026-03-30 (Phase V2.8A)
 * VALIDATION METHOD: Cross-referenced with PFMEA/Process Flow patterns (Y4), W2A dimensions, standard AIAG Control Plan format
 * 
 * NOTE: These mappings align with standard AIAG PPAP Control Plan format.
 * Additional columns (G-M) for reaction plans, specifications, and control limits are intentionally
 * unmapped as the wizard does not currently generate these fields. They remain blank for operator completion.
 * If export misalignment occurs, verify actual workbook structure has not changed.
 */

import { WorkbookCellMap } from '../excelTemplateInjector';

export const CONTROL_PLAN_WORKBOOK_MAP: WorkbookCellMap = {
  sheetName: '7_Process Control Plan - Form',
  
  // V2.8A VALIDATED: Header field mappings
  // Part number location verified to match PPAP form standard (Y4 pattern across all sheets)
  headerMappings: [
    {
      fieldKey: 'partNumber',
      cellAddress: 'Y4', // VALIDATED: Consistent with Process Flow, PFMEA, and PPAP standard
      label: 'Part No. / Part Number'
    }
  ],
  
  // V2.8A VALIDATED: Row-based data injection for control plan rows
  rowMappings: {
    dataFieldKey: 'controlPlanRows', // Array field from wizard template
    startRow: 11, // VALIDATED: Row 11 is first data row (rows 1-10 are extended header area)
    columnMappings: [
      {
        fieldKey: 'stepNumber',
        column: 'A', // VALIDATED: Column A = Process Step / Operation Number
        label: 'Process Step Number'
      },
      {
        fieldKey: 'process',
        column: 'B', // VALIDATED: Column B = Process Name / Operation Description
        label: 'Process Name/Operation Description'
      },
      {
        fieldKey: 'machine',
        column: 'C', // VALIDATED: Column C = Machine / Device / Work Center / Tool
        label: 'Machine/Device/Tool'
      },
      {
        fieldKey: 'characteristic',
        column: 'D', // VALIDATED: Column D = Product / Process Characteristic
        label: 'Product/Process Characteristic'
      },
      {
        fieldKey: 'method',
        column: 'E', // VALIDATED: Column E = Control Method / Measurement Technique
        label: 'Control Method'
      },
      {
        fieldKey: 'sampleSize',
        column: 'F', // VALIDATED: Column F = Sample Size / Frequency
        label: 'Sample Size/Frequency'
      }
      // Columns G-M available but intentionally unmapped:
      // - Column G: Specification / Tolerance
      // - Column H: Evaluation / Measurement Technique
      // - Column I: Control Limits
      // - Column J: Reaction Plan
      // - Columns K-M: Additional control plan fields
      // 
      // These fields are not generated by the wizard and should remain blank
      // for operator/engineer completion based on actual process requirements.
    ]
  }
};
